In [27]:
from sklearn.metrics.pairwise import cosine_distances
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [28]:
a1=np.array([[2,0,1,1,1,1,1,1,1,0]])
a2=np.array([[0,2,2,1,1,0,0,0,1,1]])

In [29]:
cosine_similarity(a1,a2)

array([[ 0.43519414]])

In [30]:
cosine_distances(a1, a2)

array([[ 0.56480586]])

In [32]:
vec1 = np.array([[1,1,0,1,1]])
vec2 = np.array([[0,1,0,1,1]])
#print(cosine_similarity([vec1, vec2]))
print(cosine_similarity(vec1, vec2))

[[ 0.8660254]]


In [33]:
from sklearn.metrics.pairwise import euclidean_distances
euclidean_distances(a1,a2)

array([[ 3.60555128]])